name: convo
description: Convo - Chat App by TheKami
publish_to: 'none'
version: 1.0.2+5

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.3.0
  firebase_auth: ^5.1.0
  cloud_firestore: ^5.2.0
  firebase_messaging: ^15.1.0
  geolocator: ^14.0.0
  shared_preferences: ^2.2.3
  url_launcher: ^6.2.5

flutter:
  uses-material-design: true